Update email.md
LittleSkinCommspt/LittleSkinManualDev pull request #2
Opened 2021-05-29 15:27 UTC by Restent

2021-05-29 15:27 UTC, Restent commented
@jinzhijie 您也过来看

2021-05-29 16:25 UTC, Cubik65536 requested changes
总体内容无误，但是有很多地方充斥这机翻的感觉

2021-05-29 16:25 UTC, Cubik65536 commented on en/email.md
> +Send to this Email address's mail metropolis and only be seen by Staff. We will reply emails that we think it needs reply in hurry. All replies will be send by Staff with their work email (domain is
"metropolis"？“都会“？
参考：Only the operating staff can see the emails sent to this address.

2021-05-29 16:25 UTC, Cubik65536 commented on en/email.md
> +We advise you send emails with Email address which you bind in LittleSkin, this will help us to verify user's identity for improve efficiency.
建议：绑定确实是bind，但是used更靠近日常用语

2021-05-29 16:25 UTC, Cubik65536 commented on en/email.md
> +When you roger that email from LittleSkin Staff or Community Support member, please verify email domain carefully (The part after `@` of Email address). If Email domain isn't `littlesk.in` or `commsp
> When you roger that email from

收到 - Roger，此处应该使用received

> isn't `littlesk.in` or `commspt.littlesk.in`, description that this email isn't sent by

**..., it means that it's not sent by LiittleSkin...**

2021-05-29 16:25 UTC, Cubik65536 commented on en/email.md
> +Please attention, whether Staff or Community Support member, in any way, we will not let you provide your other websites' password or login credentials. If someone let you provide your password, veri
> Please attention

**Please pay attention** ?

> whether Staff or Community Support member, in any way, we will not let you provide your other websites' password or login credentials.

在任何情况下 - 这里使用we will never更简单

我们 - 这里可以直接写 neither operating staff nor community support member

我们不会要求 - we will never ask you to provide

2021-05-29 16:25 UTC, Cubik65536 commented on en/email.md
> +If you need high timeliness technical support, please join our [Official User Group](/user-group.html) for help, instead of sending Email Ticket.
中文忘删了？

2021-05-29 22:09 UTC, Restent commented
> 总体内容无误，但是有很多地方充斥着机翻的感觉

并不是机翻
但是，很多单词是我手动查的，所以看上去可能像是机翻
放过我这个初三的吧呜呜呜呜

2021-05-29 22:11 UTC, Restent commented on en/email.md
> +Send to this Email address's mail metropolis and only be seen by Staff. We will reply emails that we think it needs reply in hurry. All replies will be send by Staff with their work email (domain is
...不是只有一个 Staff 么

2021-05-29 22:13 UTC, Restent commented on en/email.md
> +We advise you send emails with Email address which you bind in LittleSkin, this will help us to verify user's identity for improve efficiency.
这个可以考虑

2021-05-29 22:14 UTC, Restent commented on en/email.md
> +When you roger that email from LittleSkin Staff or Community Support member, please verify email domain carefully (The part after `@` of Email address). If Email domain isn't `littlesk.in` or `commsp
by LittleSkin 我觉得不可靠
应该要指定特定的群体给你回复，不能为了删一大堆东西而忽视这个

2021-05-29 22:18 UTC, Restent commented on en/email.md
> +Please attention, whether Staff or Community Support member, in any way, we will not let you provide your other websites' password or login credentials. If someone let you provide your password, veri
1.Pay attention 确实也没错
2.可以考虑

2021-05-29 23:28 UTC, Cubik65536 commented on en/email.md
> +Send to this Email address's mail metropolis and only be seen by Staff. We will reply emails that we think it needs reply in hurry. All replies will be send by Staff with their work email (domain is
> ...不是只有一个 Staff 么

原文是运营组，任何不清楚具体有谁的人都可能会认为是多个人组成，我们是否应该使用Operating Team？
另外，`Only the operating staff`并非复数

2021-05-29 23:29 UTC, Cubik65536 commented on en/email.md
> +When you roger that email from LittleSkin Staff or Community Support member, please verify email domain carefully (The part after `@` of Email address). If Email domain isn't `littlesk.in` or `commsp
> by LittleSkin 我觉得不可靠
> 应该要指定特定的群体给你回复，不能为了删一大堆东西而忽视这个

你翻译的版本内也是by LittleSkin，此处仅仅指出`则说明`不能直接翻译为`description that`

2021-05-31 01:31 UTC, jinzhijie requested changes
Staff? 复数呢？s 呢？
Community Support? 应该是 Community Support Group/Team 吧？
Community Support member? 就一个人？s 哪里去了？

2021-06-01 14:54 UTC, Restent commented
> Staff? 复数呢？s 呢？
> Community Support? 应该是 Community Support Group/Team 吧？
> Community Support member? 就一个人？s 哪里去了？

你 s 我 s 大家 s（
下次我注意

2021-06-02 01:13 UTC, Cubik65536 commented
复数确实是个问题，把语法部分改了先合并以后再优化吧

2021-06-22 19:45 UTC, Cubik65536 commented
@jinzhijie 可以Review了

2021-06-23 00:45 UTC, jinzhijie approved these changes

2021-06-23 00:45 UTC, merged