Update report.md
LittleSkinCommspt/LittleSkinManualDev pull request #3
Opened 2021-05-31 12:53 UTC by Restent

咕咕咕

2021-05-31 13:41 UTC, Cubik65536 requested changes
「首先；其次」应该使用Firstly，secondly而非First，sencond。

其他的地方仍可提高，不过不影响理解。

2021-05-31 13:43 UTC, Restent commented
dalao 帮我吧，我眼困了（


2021年5月31日21:42 来自 ***@***.***:

>
>
>
>
> @Cubik65536>  requested changes on this pull request.
>
>
> 「首先；其次」应该使用Firstly，secondly而非First，sencond。
>
>
> 其他的地方仍可提高，不过不影响理解。
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, > view it on GitHub <https://github.com/LittleSkinCommspt/LittleSkinManualDev/pull/3#pullrequestreview-672323824>> , or > unsubscribe <https://github.com/notifications/unsubscribe-auth/AMVHCWT557VDE4ZWMKSXF33TQOG3DANCNFSM4522ZCBQ>> .
>
>
>

2021-05-31 14:45 UTC, Cubik65536 requested changes
整体内容无误，但仍有部分语法问题

我已留下部分改进建议，希望能够帮到你

Best regards,

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +# How to request question
根据文件名称提出更改建议：
How to report a question

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +Everything are not possible to perfect, LittleSkin is also like this.
提出建议，即供参考：

Nothing is perfect, nor LittleSkin.

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +If you have any problem that you use LittleSkin (including but not limited to: texture can't display, website have bugs etc.), don't utterly discomfited， please understand the following content fully
> ...that you use LittleSkin...

...**while** you use LittleSkin...

> including but not limited to

非常好

> ... texture can't display, website have bugs etc.

- etc前面要写逗号 `..., etc.`

- 更改建议：textures aren't showing, bugs on the website, etc.

> 气急败坏 -》utterly discomfited

翻译确实没错，但是有点怪异，先这么写吧

> please understand the following content fully

建议：please fully understand the following content

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +## The first reaction when having a problem
> when

更改建议：while

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +First, you should check if this is your problem at first. At many times, LittleSkin can run normally. If you get an error, please make sure that this isn't your problem at first: Network error, Opera
> First,

**Firstly, **

> if this is your problem

更改建议：if it's your problem

> At many times,

更改建议： For most of the time,

> Operating error

更改建议：wrong operation

> even your browser error might can't let you use LittleSkin normally

更改建议：even your browser's error can makes you run into problem while using LittleSkin 

> please judgment with

please judge with

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +Second, you should read [FAQ](/faq.html) at first. At many times, your problem might also trouble many people, and these problem are already have solution. At this situation, read FAQ directly can so
> Second,

Secondly, 

> at first

删掉它，secondly和first相互冲突

> At many time, 

更改建议：Sometimes,

> your problem might also trouble many people

更改建议：your problem might troubled many other people

> and these problem are already have solution

更改建议：
- and these problems have already a solution
- and there's already a solution for these problems

> At this situation

In this situation

> read FAQ

read the FAQ

> fastly

quickly（fastly不是个单词啊！）

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +If you sure that you don't have any problem, and your problem isn't in FAQ, you can prepare to report problem.
> you don't have any problem

这么写是指：你没有遇到任何问题

更改建议：If you're sure that it's not your problem

> in FAQ

in the FAQ

> report problem

report the problem

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +Understang this article fully can help you ask questions better, and also receive the reply and the right answer fastly. But please attention, the team of How To Ask Questions The Smart Way is only p
> Understang this article fully

Fully understand this article

> fastly

**quickly** !!!

> But please attention

But please **pay** attention

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +## Operation team isn't god
更改建议：Operating staffs aren't god

2021-05-31 14:45 UTC, Cubik65536 commented on report.md
> +Looks like many of "you" are
更改建议：It seems to me most of you don't know it.

2021-06-01 14:43 UTC, Cubik65536 commented
已基于该版翻译进行优化并补齐其他翻译，查看 #1

2021-06-01 14:43 UTC, closed without merging

2021-06-01 14:51 UTC, jinzhijie commented on report.md
> +If you have any problem that you use LittleSkin (including but not limited to: texture can't display, website have bugs etc.), don't utterly discomfited， please understand the following content fully
① while 引导的时态状语从句应该用现在时吧？所以不应该是 `... while you are using LittleSkin ...` 么？

③ 可以改成类似于 wrong textures 这种，至少得是个名词