Update faq.md
LittleSkinCommspt/LittleSkinManualDev pull request #4
Opened 2021-06-27 05:52 UTC by Restent

要睡觉了，之后慢慢翻

2021-06-28 00:43 UTC, Cubik65536 commented
已经转换为草稿，等翻译完成之后再做review

2021-07-28 01:50 UTC, Cubik65536 approved these changes
LGTM! 需要提高但是可以之后再做改进

2021-08-14 22:25 UTC, tnqzh123 requested changes
omg…这个翻译质量真的一言难尽，很多地方都有很浓的机翻味，不过也有的地方翻的不错

翻译是门技术活，有些东西是只可意会不可言传的，不能逐字逐句地根据字面意思翻译。可以根据语境对文本进行适当的修改，意思到了就行。

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +Please check your email's trash can at first. If you can't find verify email in trash can, please try send verify email again.
trash can 改成 trash folder 比较好，毕竟不是真正的“桶”，也有的邮箱把这个文件夹叫 Junk Email 的

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +## Station usage related
Website Related

这种短标题中超过三个字符的单词的首字母要大写

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +### Can't receive verify email？
用 verification email，verify 是动词，这个句子里已经有一个 receive 了

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +Please check your email's trash can at first. If you can't find verify email in trash can, please try send verify email again.
verification email

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +If you still can't receive verify email, please check your email that bind your account is correct, if incorrect, please change it to your correct email.
If you still cannot receive verification email, please check your whether email address that bind your account is correct. If not, please change it to the correct one.

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +If you sure your email that bind your account is correct, and verify email can't find in your trash can, please join our [User Group](/user-group.html), contact staff to process.
If you sure your email address bound to your account is correct, and the verification email cannot be found in the Junk Email folder, please join our [User Group](/user-group.html), contact staffs to address it.

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +### My profile are have by others, I can get it back?
My profile has been taken by others, may I get it back?

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +No. The chance of having the same name is very high, change players' owner is unfair to both users, so whether you are an anchor or a rich people, we don't provide the service that change players' ow
No. The chance of having the same name is very high, change profiles' owner is unfair to both users, so we won't change profiles' owner for everyone.

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +If you find that your player's name has been occupied by others, you can contact this player's owner. If you talk to this player's owner properly (not use a strong tone to talk to this player's owner
occupied 改 taken，站里用的就是 taken

BTW 这句翻的很不错

2021-08-14 22:25 UTC, tnqzh123 commented on en/faq.md
> +There is a special case: you have Genuine Minecraft account, and your Genuine Minecraft ID just the player's name that be occupied by others. In this condition, you can pass [Bind your Genuine Minecr
However, there is a special case: you have a Mojang account with Genuine Minecraft, and your Genuine Minecraft player name is just the player name that be taken by others. In this situation, you can get your profile by [Bind Your Mojang Account](/newbee/player.html).

2021-08-14 22:31 UTC, tnqzh123 commented
可以多尝试用一些完成时、被动语态、各种从句这种在中国的英语考试里看起来很高大上的语法，这样作为文档这种比较 serious 的场合，内容看起来会更棒一点。（其实我也说不出到底是哪里更棒，可能是比较装逼吧）

不用担心用错，大胆用就行，大不了我给你 review 的时候改过来。其实这些在中国的英语考试里看起来很高大上的语法在以英语为主要受众的母语的社区中这些是非常常见的东西。

2021-08-14 22:33 UTC, Cubik65536 commented
我过两天抽时间改一下

2021-08-15 04:52 UTC, Restent commented
其实有些单词我是从 Google Translate 抓过来的🌚
我先看看需要更改的内容

2022-05-06 09:58 UTC, closed without merging